// Copyright (c) 2012 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     base/android/jni_generator/jni_generator.py
// For
//     org/chromium/base/PathService

#ifndef org_chromium_base_PathService_JNI
#define org_chromium_base_PathService_JNI

#include <jni.h>
#include "base/android/jni_generator/jni_generator_helper.h"
// Step 1: forward declarations.
namespace {
const char kPathServiceClassPath[] = "org/chromium/base/PathService";
// Leaking this jclass as we cannot use LazyInstance from some threads.
jclass g_PathService_clazz = NULL;

}  // namespace

namespace base {
namespace android {

static void Override(JNIEnv* env, jclass jcaller,
    jint what,
    jstring path);

// Step 2: method stubs.

// Step 3: RegisterNatives.

static const JNINativeMethod kMethodsPathService[] = {
    { "nativeOverride",
"("
"I"
"Ljava/lang/String;"
")"
"V", reinterpret_cast<void*>(Override) },
};

static bool RegisterNativesImpl(JNIEnv* env) {
  g_PathService_clazz = reinterpret_cast<jclass>(env->NewGlobalRef(
      base::android::GetClass(env, kPathServiceClassPath).obj()));

  const int kMethodsPathServiceSize = arraysize(kMethodsPathService);

  if (env->RegisterNatives(g_PathService_clazz,
                           kMethodsPathService,
                           kMethodsPathServiceSize) < 0) {
    jni_generator::HandleRegistrationError(
        env, g_PathService_clazz, __FILE__);
    return false;
  }

  return true;
}

}  // namespace android
}  // namespace base

#endif  // org_chromium_base_PathService_JNI
