/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_common_luakit_LuaHelper */
#ifndef _Included_com_common_luakit_LuaHelper
#define _Included_com_common_luakit_LuaHelper

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_com_common_luakit_LuaHelper_startLuaKitNative
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
