# This file is generated by auto-build.py, DON'T modify manually!

# Module: openssl
# Type: None
# Dependencies: crypto ssl


LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE := openssl

LOCAL_STATIC_LIBRARIES += engines

LOCAL_STATIC_LIBRARIES += crypto \
                          ssl



