// Copyright (c) 2012 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     base/android/jni_generator/jni_generator.py
// For
//     org/chromium/base/SysUtils

#ifndef org_chromium_base_SysUtils_JNI
#define org_chromium_base_SysUtils_JNI

#include <jni.h>
#include "base/android/jni_generator/jni_generator_helper.h"

// Step 1: forward declarations.
namespace {
const char kSysUtilsClassPath[] = "org/chromium/base/SysUtils";
// Leaking this jclass as we cannot use LazyInstance from some threads.
jclass g_SysUtils_clazz = NULL;

}  // namespace

// Step 2: method stubs.

static base::subtle::AtomicWord g_SysUtils_amountOfPhysicalMemoryKB = 0;
static jint Java_SysUtils_amountOfPhysicalMemoryKB(JNIEnv* env) {
  /* Must call RegisterNativesImpl()  */
  CHECK_CLAZZ(env, g_SysUtils_clazz,
      g_SysUtils_clazz, 0);
  jmethodID method_id =
      base::android::MethodID::LazyGet<
      base::android::MethodID::TYPE_STATIC>(
      env, g_SysUtils_clazz,
      "amountOfPhysicalMemoryKB",

"("
")"
"I",
      &g_SysUtils_amountOfPhysicalMemoryKB);

  jint ret =
      env->CallStaticIntMethod(g_SysUtils_clazz,
          method_id);
  jni_generator::CheckException(env);
  return ret;
}

static base::subtle::AtomicWord g_SysUtils_isLowEndDevice = 0;
static jboolean Java_SysUtils_isLowEndDevice(JNIEnv* env) {
  /* Must call RegisterNativesImpl()  */
  CHECK_CLAZZ(env, g_SysUtils_clazz,
      g_SysUtils_clazz, false);
  jmethodID method_id =
      base::android::MethodID::LazyGet<
      base::android::MethodID::TYPE_STATIC>(
      env, g_SysUtils_clazz,
      "isLowEndDevice",

"("
")"
"Z",
      &g_SysUtils_isLowEndDevice);

  jboolean ret =
      env->CallStaticBooleanMethod(g_SysUtils_clazz,
          method_id);
  jni_generator::CheckException(env);
  return ret;
}

// Step 3: RegisterNatives.

static bool RegisterNativesImpl(JNIEnv* env) {
  g_SysUtils_clazz = reinterpret_cast<jclass>(env->NewGlobalRef(
      base::android::GetClass(env, kSysUtilsClassPath).obj()));

  return true;
}

#endif  // org_chromium_base_SysUtils_JNI
