/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_common_luakit_LuaNotificationListener */
#ifndef _Included_com_common_luakit_LuaNotificationListener
#define _Included_com_common_luakit_LuaNotificationListener
#include "notification_listener_impl.h"
#include "JNIConversionDecl.h"
#include "LogicModel.h"

namespace JNIConversion {
	DECLARE_JAVAOBJECT_CONVERSION_MODEL(scoped_refptr<NotificationListenerImpl>, LogicModel::NotificationListener)
}

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_common_luakit_LuaNotificationListener
 * Method:    nativeNewNotificationListener
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_common_luakit_LuaNotificationListener_nativeNewNotificationListener
  (JNIEnv *, jobject);

/*
 * Class:     com_common_luakit_LuaNotificationListener
 * Method:    nativeAddObserver
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_common_luakit_LuaNotificationListener_nativeAddObserver
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_common_luakit_LuaNotificationListener
 * Method:    nativeRemoveObserver
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_common_luakit_LuaNotificationListener_nativeRemoveObserver
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
