/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tencent_wework_foundation_common_NativeHandleHolder */

#ifndef _Included_com_common_luakit_NativeHandleHolder
#define _Included_com_common_luakit_NativeHandleHolder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_common_luakit_NativeHandleHolder
 * Method:    nativeFree
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_common_luakit_NativeHandleHolder_nativeFree
  (JNIEnv *, jobject, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
