/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_common_luakit_Demo */
#ifndef _Included_com_common_luakit_Demo
#define _Included_com_common_luakit_Demo

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jobjectArray JNICALL Java_com_common_luakit_Demo_getWeatherNative
  (JNIEnv *, jclass);

JNIEXPORT void JNICALL Java_com_common_luakit_Demo_loadWeatherNative
  (JNIEnv *, jclass, jobject);

JNIEXPORT void JNICALL Java_com_common_luakit_Demo_threadTestNative
        (JNIEnv *, jclass);

JNIEXPORT void JNICALL Java_com_common_luakit_Demo_notificationTestNative
        (JNIEnv *, jclass);

JNIEXPORT void JNICALL Java_com_common_luakit_Demo_asynSocketTestNative
        (JNIEnv *, jclass);

JNIEXPORT void JNICALL Java_com_common_luakit_Demo_dbTestNative
        (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
