/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_common_luakit_NotificationHelper */
#ifndef _Included_com_common_luakit_NotificationHelper
#define _Included_com_common_luakit_NotificationHelper

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_common_luakit_NotificationHelper
 * Method:    postNotificationNative
 * Signature: (ILjava/lang/Object;)V
 */
JNIEXPORT jlong JNICALL Java_com_common_luakit_NotificationHelper_postNotificationNative
  (JNIEnv *, jclass, jint ,jobject);

#ifdef __cplusplus
}
#endif
#endif
